accounts/urls.py
from django.urls import path
from .views import SignUpView, CookListView, CookDetailView, CookUpdateView

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
]

kitchen/urls.py
from django.urls import path

from .views import (
    IndexView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    IngredientListView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
)

app_name = "kitchen"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),

    # Dish types
    path("dish-types/", DishTypeListView.as_view(),
         name="dishtype-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(),
         name="dishtype-create"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(),
         name="dishtype-update"),
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(),
         name="dishtype-delete"),

    # Dishes
    path("dishes/", DishListView.as_view(),
         name="dish-list"),
    path("dishes/create/", DishCreateView.as_view(),
         name="dish-create"),
    path("dishes/<int:pk>/", DishDetailView.as_view(),
         name="dish-detail"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(),
         name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(),
         name="dish-delete"),

    # Ingredients
    path("ingredients/", IngredientListView.as_view(),
         name="ingredient-list"),
    path("ingredients/create/", IngredientCreateView.as_view(),
         name="ingredient-create"),
    path("ingredients/<int:pk>/update/", IngredientUpdateView.as_view(),
         name="ingredient-update"),
    path("ingredients/<int:pk>/delete/", IngredientDeleteView.as_view(),
         name="ingredient-delete"),
]

restaurant_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("kitchen.urls")),
]

templates/includes/pagination.html
{% if is_paginated %}
  <nav class="mt-4">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" 
             href="?{% if querystring %}{{ querystring }}&{% endif %}page={{ page_obj.previous_page_number }}">
            Previous
          </a>
        </li>
      {% else %}
        <li class="page-item disabled"><span class="page-link">Previous</span></li>
      {% endif %}

      <li class="page-item disabled">
        <span class="page-link">Page {{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" 
             href="?{% if querystring %}{{ querystring }}&{% endif %}page={{ page_obj.next_page_number }}">
            Next
          </a>
        </li>
      {% else %}
        <li class="page-item disabled"><span class="page-link">Next</span></li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/sidebar.html
<div class="list-group">
  <a class="list-group-item list-group-item-action" href="{% url 'kitchen:index' %}">Dashboard</a>
  <a class="list-group-item list-group-item-action" href="{% url 'kitchen:dish-list' %}">Dishes</a>
  <a class="list-group-item list-group-item-action" href="{% url 'kitchen:dishtype-list' %}">Dish types</a>
  <a class="list-group-item list-group-item-action" href="{% url 'kitchen:ingredient-list' %}">Ingredients</a>  
  <a class="list-group-item list-group-item-action" href="{% url 'accounts:cook-list' %}">Cooks</a>
    
  {% if not user.is_authenticated %}
    <a class="list-group-item list-group-item-action"
       href="{% url 'accounts:signup' %}">
      Sign up
    </a>
  {% endif %}
    
  {% if user.is_authenticated %}  
  <form method="post" action="{% url 'logout' %}" class="list-group-item">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button class="btn btn-link p-0 text-decoration-none" type="submit">Logout</button>
  </form>
  {% endif %}
    
</div>